services:
  postgres:
    image: postgres:15
    container_name: fleet-postgres
    environment:
      POSTGRES_DB: fleetdb
      POSTGRES_USER: fleetuser
      POSTGRES_PASSWORD: fleetpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  python-service:
    build: ../python-service
    container_name: fleet-python
    ports:
      - "8000:8000"
  app:
    build: .
    container_name: fleet-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fleetdb
      SPRING_DATASOURCE_USERNAME: fleetuser
      SPRING_DATASOURCE_PASSWORD: fleetpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8"
    depends_on:
      - postgres
      - python-service
volumes:
  postgres_data:
