apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-backend
  namespace: quant-trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading-backend
  template:
    metadata:
      labels:
        app: trading-backend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: trading-backend
          image: europe-west1-docker.pkg.dev/strong-minutia-497313-f4/trading-repo/trading-backend:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/quantdb
            - name: SPRING_DATASOURCE_USERNAME
              value: quant_user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: PYTHON_QUANT_URL
              value: http://quant-ai-workers:8003
            - name: PYTHON_LSTM_URL
              value: http://quant-ai-workers:8004
            - name: PYTHON_RAG_URL
              value: http://quant-ai-workers:8002
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: trading-backend
  namespace: quant-trading
spec:
  selector:
    app: trading-backend
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: trading-backend-keda
  namespace: quant-trading
spec:
  scaleTargetRef:
    name: trading-backend
  minReplicaCount: 1  # Η Java κρατάει 1 ελάχιστο για να απαντάει στα API ακαριαία
  maxReplicaCount: 5
  triggers:
    - type: cpu
      metadata:
        value: "70"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fleet-ingress
  namespace: quant-trading
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: trading-backend
                port:
                  number: 8080
